name: 'Amazon ECS "Deploy Task Definition" Action for GitHub Actions'
description: 'Registers an Amazon ECS task definition, and deploys it to an ECS service'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The path to the ECS task definition file to register'
    required: true
  cluster:
    description: "The name of the ECS service's cluster.  Will default to the 'default' cluster"
    required: true
  subnet:
    description: "The subnets that the ECS task will belong with."
    required: true
  security-group:
    description: "The security group that the ECS task will belong with."
outputs:
  task-definition-arn:
    description: 'The ARN of the registered ECS task definition'
runs:
  using: 'node18'
  main: 'dist/index.js'
